version: '3'
services:

  web:
    container_name: server
    image: sunwupark/mappin-server
    expose:
      - 8080
    ports:
      - 8080:8080

  nginx:
    container_name: nginx
    image: sunwupark/mappin-nginx
    ports:
      - 80:80
    depends_on:
      - web